/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
static yyconst short int yy_accept[381] =
    {   0,
       88,   88,   28,   28,   87,   87,   57,   57,   73,   73,
        0,    0,    0,    0,   83,   83,   85,   85,    0,    0,
        0,    0,    0,    0,    0,    0,   90,   89,   88,   89,
       89,   89,   89,   89,   89,   29,   28,   28,   29,   29,
       87,   89,   89,   50,   50,   50,   50,   50,   50,   50,
       86,   57,   54,   89,   89,   89,   51,   56,   89,   55,
       89,   53,   73,   66,   89,   89,   89,   71,   89,   71,
       71,   71,   72,   67,   76,   76,   74,   75,   60,   89,
       61,   59,   83,   77,   89,   89,   89,   80,   89,   80,
       81,   78,   85,   89,   89,   82,   84,   64,   89,   89,

       64,   89,   89,   89,   63,   63,   35,   89,   34,   89,
       33,   33,   33,   33,   33,   48,   89,   89,   89,   47,
       49,   47,   44,   45,   89,   89,   89,   46,   46,   88,
        2,    1,    0,    0,    0,    0,    0,    0,   28,   27,
       26,    3,   87,   15,    4,   42,   50,   50,   50,   50,
       50,   50,   50,   50,   57,   51,   51,   16,    5,    0,
        0,    0,    0,    0,    0,   43,   53,   73,   71,   71,
       17,    6,    0,    0,    0,    0,    0,   71,   71,   70,
       18,    7,   19,    8,   59,   83,   80,   80,   20,    9,
        0,    0,    0,    0,    0,   80,   85,    0,   84,   21,

       10,   82,   64,    0,   64,    0,   62,    0,   65,   64,
       63,   63,   22,   11,    0,   63,   36,   23,   12,   33,
       33,   33,   33,   33,   47,   47,   24,   13,    0,   47,
       46,   46,   25,   14,    0,   46,    1,    1,    0,    0,
        0,   31,    0,    0,    3,    3,    4,    4,   42,   50,
       50,   50,   50,   50,   50,   50,    5,    5,   51,    0,
        0,    0,    0,    0,   43,    6,    6,   71,    0,    0,
        0,    0,    0,    0,   69,    7,    7,    8,    8,    9,
        9,   80,    0,    0,    0,    0,    0,    0,   10,   10,
       65,   11,   11,   63,   12,   12,   33,   33,   32,   33,

       13,   13,   47,   14,   14,   46,    0,    0,    0,    0,
       50,   50,   50,   38,   50,   50,   41,    0,    0,    0,
        0,    0,    0,   68,    0,   79,    0,   33,   33,    0,
        0,    0,   50,   50,   50,   50,   52,   33,    0,    0,
       50,   50,   50,    0,    0,   50,   50,   50,    0,    0,
       58,   50,   39,   30,    0,   50,   39,    0,   40,    0,
       40,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   37,   37,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    1,    6,
        7,    8,    1,    9,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    1,   14,   15,
       16,   17,    1,   18,   19,   19,   20,   19,   19,   19,
       19,   19,   21,   19,   19,   19,   19,   19,   19,   22,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
        1,    1,    1,    1,    1,    1,   23,   24,   25,   26,

       27,   28,   29,   19,   30,   31,   19,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   19,   19,
       43,   19,   44,    1,   45,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[46] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1
    } ;

static yyconst short int yy_base[413] =
    {   0,
        0,   41,    2,    5,   83,    0,  128,    0,  173,    0,
        3,    6,  218,    0,  263,    0,  308,    0,  353,    0,
      398,    0,  443,    0,  488,    0,  890,  891,   17,   13,
      854,  856,    0,  847,  851,  891,   20,   29,  873,   28,
       35,   33,    0,    0,   19,  852,  849,  841,  843,  850,
      891,  875,  891,  865,  864,   44,   16,  891,   35,  891,
        0,    0,   57,  891,  863,  862,   54,   44,   43,    0,
      840,  835,  891,  891,  891,   70,  891,  891,  891,  526,
      891,    0,   61,  891,  859,  858,  527,   68,  513,    0,
      891,  891,  534,   20,  536,    0,  891,    2,  865,  537,

      865,  855,  854,  538,  541,    0,  891,  852,  891,  541,
        0,  830,  832,  829,  827,  891,  848,  847,  547,  545,
      891,    0,  891,  891,  846,  845,  549,  549,    0,  561,
      891,  854,  815,  820,  818,  813,  829,  821,  563,  891,
      891,  847,  565,  891,  846,    0,    0,  809,  806,  811,
      805,  805,  813,  810,  837,  558,  827,  891,  836,  825,
      811,  806,  794,  807,  792,    0,    0,  570,  563,  819,
      891,  828,  817,  792,  543,  548,  801,    0,  801,    0,
      891,  823,  891,  822,    0,  575,  568,  811,  891,  820,
      809,  784,  553,  555,  793,    0,  582,   31,  891,  891,

      816,    0,  582,  583,  814,  812,  891,  586,  812,  811,
      581,  801,  891,  810,  799,    0,  891,  891,  808,    0,
      769,  774,  768,  777,  585,  793,  891,  802,  791,    0,
      588,  790,  891,  799,  788,    0,  797,  891,  775,  775,
      762,  891,  756,  769,  791,  891,  790,  891,    0,  767,
      767,  767,  785,  748,  753,  754,  782,  891,  771,  757,
      574,  750,  748,  756,    0,  776,  891,  765,  760,  759,
      758,  757,  756,  735,    0,  768,  891,  767,  891,  766,
      891,  755,  750,  749,  748,  747,  746,  725,  758,  891,
      756,  756,  891,  745,  754,  891,  732,  732,    0,  728,

      750,  891,  739,  748,  891,  737,  717,  708,  709,  716,
      722,  712,  703,  891,  721,  701,    0,  723,  722,  721,
      720,  719,  718,  891,  717,  891,  716,  700,  691,  703,
      689,  703,  613,  623,  614,  615,  891,  619,  641,  640,
      617,  622,  607,    0,  598,  635,  615,  631,  622,  600,
      891,  595,  629,  891,  602,  604,  626,  603,  624,  623,
      622,  598,  590,  583,  584,  578,  598,  584,  588,  583,
      575,  599,  600,  603,  604,  605,  608,  610,  609,  891,
      652,  655,  658,  540,  660,   43,  662,  664,  666,  668,
      670,  673,  675,  677,  679,  681,  684,  687,  690,  692,

      695,  697,  700,  703,  706,  709,  712,  715,  718,  721,
      724,   13
    } ;

static yyconst short int yy_def[413] =
    {   0,
      381,  381,  382,  382,  380,    5,  380,    7,  380,    9,
      383,  383,  380,   13,  380,   15,  380,   17,  380,   19,
      380,   21,  380,   23,  380,   25,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  384,  385,  385,  385,  385,  385,  385,  385,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      386,  387,  380,  380,  380,  380,  380,  380,  380,  388,
      388,  388,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  389,  380,  380,  380,  380,  380,  380,  380,  390,
      380,  380,  380,  380,  380,  391,  380,  380,  392,  380,

      380,  380,  380,  380,  380,  393,  380,  380,  380,  380,
      394,  394,  394,  394,  394,  380,  380,  380,  380,  380,
      380,  395,  380,  380,  380,  380,  380,  380,  396,  380,
      380,  397,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  398,  380,  380,  399,  400,  385,  385,  385,  385,
      385,  385,  385,  385,  380,  380,  380,  380,  401,  380,
      380,  380,  380,  380,  380,  402,  387,  380,  380,  380,
      380,  403,  380,  380,  380,  380,  380,  388,  388,  388,
      380,  404,  380,  405,  389,  380,  380,  380,  380,  406,
      380,  380,  380,  380,  380,  390,  380,  380,  380,  380,

      407,  391,  380,  380,  380,  392,  380,  380,  380,  380,
      380,  380,  380,  408,  380,  393,  380,  380,  409,  394,
      394,  394,  394,  394,  380,  380,  380,  410,  380,  395,
      380,  380,  380,  411,  380,  396,  397,  380,  380,  380,
      380,  380,  380,  380,  398,  380,  399,  380,  400,  385,
      385,  385,  385,  385,  385,  385,  401,  380,  380,  380,
      380,  380,  380,  380,  402,  403,  380,  380,  380,  380,
      380,  380,  380,  380,  388,  404,  380,  405,  380,  406,
      380,  380,  380,  380,  380,  380,  380,  380,  407,  380,
      380,  408,  380,  380,  409,  380,  394,  394,  394,  394,

      410,  380,  380,  411,  380,  380,  380,  380,  380,  380,
      385,  385,  385,  380,  385,  385,  385,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  394,  394,  380,
      380,  380,  385,  385,  385,  385,  380,  394,  380,  380,
      385,  385,  385,  412,  380,  385,  385,  385,  412,  380,
      380,  385,  380,  380,  380,  385,  380,  380,  385,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,    0,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,

      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380
    } ;

static yyconst short int yy_nxt[937] =
    {   0,
      380,   29,   29,   37,   38,  203,   37,   38,  204,   39,
      205,   30,   39,   40,   76,  349,   40,   76,  130,  130,
      131,  139,  139,  198,  132,   31,  160,   32,  156,   33,
      139,  139,  135,  136,  198,  141,  143,  143,   34,  142,
      144,   35,   29,   29,  145,  166,   77,   78,  148,   77,
       78,  158,   30,  149,  173,  159,  169,  161,  168,  168,
      162,  171,  186,  186,  199,  172,   31,  163,   32,  174,
       33,  175,  164,  165,  176,  199,  177,  181,  191,   34,
      187,  182,   35,   28,   41,   41,   28,   28,   28,   28,
       28,   28,   28,   28,   42,   28,   28,   28,   28,   28,

       43,   44,   44,   44,   44,   44,   44,   44,   45,   44,
       46,   44,   47,   48,   44,   44,   44,   44,   49,   44,
       44,   44,   50,   44,   44,   44,   28,   51,   28,   28,
       28,   52,   28,   28,   28,   28,   53,   54,   55,   56,
       57,   58,   59,   60,   28,   61,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   28,   28,   28,   63,   63,   28,   28,   64,   64,
       28,   28,   65,   66,   67,   68,   28,   69,   28,   28,
       28,   70,   70,   70,   70,   71,   70,   70,   70,   70,

       70,   70,   70,   70,   70,   70,   70,   72,   70,   70,
       70,   70,   70,   70,   70,   70,   73,   74,   28,   28,
       28,   28,   28,   28,   28,   28,   79,   28,   28,   80,
       28,   81,   28,   28,   28,   28,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   28,   28,   28,   83,   83,   28,   28,   84,   84,
       28,   28,   85,   86,   87,   88,   28,   89,   28,   28,
       28,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,

       90,   90,   90,   90,   90,   90,   91,   92,   28,   93,
       93,   94,   28,   28,   28,   28,   28,   28,   28,   95,
       28,   28,   28,   28,   28,   28,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   28,   97,   28,   28,   28,   98,   99,   28,  100,
       28,  101,  102,  103,  104,  105,   28,   28,   28,   28,
       28,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,   28,   28,   28,   28,

       28,   28,   28,  107,  108,   28,  109,   28,   28,  110,
       28,   28,   28,   28,   28,   28,  111,  111,  111,  111,
      111,  111,  111,  112,  111,  113,  111,  114,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  115,
      111,   28,   28,   28,   28,   28,   28,   28,  116,  116,
       28,  116,  117,  118,  119,  120,  121,   28,   28,   28,
       28,  122,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  122,   28,   28,   28,   28,
       28,   28,   28,  123,  124,   28,  123,  125,  126,  127,

      128,   28,   28,   28,   28,   28,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,   28,   28,  183,  189,  197,  197,  184,  190,  192,
      208,  193,  146,  200,  194,  213,  195,  201,  218,  214,
      209,  215,  219,  211,  227,  229,  233,  225,  228,  235,
      234,  231,  130,  130,  139,  139,  143,  143,  160,  270,
      156,  168,  168,  173,  272,  169,  186,  186,  191,  284,
      187,  286,  271,  197,  197,  203,  208,  273,  204,  208,
      205,  215,  285,  211,  287,  229,  209,  225,  235,  209,

      231,  319,  373,  373,  374,  374,  375,  375,  377,  376,
      376,  377,  379,  379,  372,  320,  371,  370,  369,  368,
      367,  366,  365,  364,  363,  361,  362,  361,  360,  357,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      348,  347,  346,  345,  344,  299,  343,  342,  378,  253,
      341,  378,   28,   28,   28,   36,   36,   36,   75,   75,
       75,  147,  147,  167,  167,  178,  178,  185,  185,  196,
      196,  202,  202,  206,  206,  206,  216,  216,  220,  220,
      230,  230,  236,  236,  237,  237,  237,  245,  245,  245,
      247,  247,  247,  249,  249,  257,  257,  257,  265,  265,

      266,  266,  266,  276,  276,  276,  278,  278,  278,  280,
      280,  280,  289,  289,  289,  292,  292,  292,  295,  295,
      295,  301,  301,  301,  304,  304,  304,  340,  339,  242,
      299,  338,  326,  324,  337,  337,  337,  337,  337,  337,
      336,  335,  253,  334,  333,  332,  331,  242,  330,  306,
      305,  303,  302,  299,  329,  328,  296,  294,  293,  291,
      290,  327,  326,  326,  326,  326,  326,  282,  281,  279,
      277,  325,  324,  324,  324,  324,  324,  268,  267,  323,
      322,  321,  318,  259,  258,  317,  316,  315,  314,  313,
      312,  311,  248,  246,  242,  310,  309,  308,  307,  238,

      306,  305,  232,  303,  302,  226,  300,  299,  298,  297,
      296,  294,  293,  212,  210,  291,  207,  210,  290,  288,
      283,  282,  281,  188,  279,  277,  275,  274,  269,  268,
      267,  170,  264,  263,  262,  261,  260,  259,  258,  157,
      155,  256,  255,  254,  253,  252,  251,  250,  248,  246,
      244,  243,  242,  241,  240,  239,  238,  232,  231,  226,
      225,  224,  223,  222,  221,  217,  212,  211,  210,  207,
      188,  187,  180,  179,  170,  169,  157,  156,  155,  154,
      153,  152,  151,  150,  140,  138,  137,  134,  133,  380,
       27,  380,  380,  380,  380,  380,  380,  380,  380,  380,

      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380
    } ;

static yyconst short int yy_chk[937] =
    {   0,
        0,    1,    1,    3,    3,   98,    4,    4,   98,    3,
       98,    1,    4,    3,   11,  412,    4,   12,   29,   29,
       30,   37,   37,   94,   30,    1,   57,    1,   57,    1,
       38,   38,   33,   33,  198,   40,   41,   41,    1,   40,
       42,    1,    2,    2,   42,  386,   11,   11,   45,   12,
       12,   56,    2,   45,   68,   56,   68,   59,   63,   63,
       59,   67,   83,   83,   94,   67,    2,   59,    2,   69,
        2,   69,   59,   59,   69,  198,   69,   76,   88,    2,
       88,   76,    2,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   21,   21,

       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,

       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   80,   87,   93,   93,   80,   87,   89,
      100,   89,  384,   95,   89,  104,   89,   95,  110,  104,
      100,  105,  110,  105,  119,  120,  127,  120,  119,  128,
      127,  128,  130,  130,  139,  139,  143,  143,  156,  175,
      156,  168,  168,  169,  176,  169,  186,  186,  187,  193,
      187,  194,  175,  197,  197,  203,  204,  176,  203,  208,
      203,  211,  193,  211,  194,  225,  204,  225,  231,  208,

      231,  261,  372,  373,  372,  373,  374,  375,  376,  374,
      375,  377,  379,  378,  371,  261,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  353,  352,  350,  349,  348,  347,  346,  345,
      343,  342,  341,  340,  339,  338,  336,  335,  376,  334,
      333,  377,  381,  381,  381,  382,  382,  382,  383,  383,
      383,  385,  385,  387,  387,  388,  388,  389,  389,  390,
      390,  391,  391,  392,  392,  392,  393,  393,  394,  394,
      395,  395,  396,  396,  397,  397,  397,  398,  398,  398,
      399,  399,  399,  400,  400,  401,  401,  401,  402,  402,

      403,  403,  403,  404,  404,  404,  405,  405,  405,  406,
      406,  406,  407,  407,  407,  408,  408,  408,  409,  409,
      409,  410,  410,  410,  411,  411,  411,  332,  331,  330,
      329,  328,  327,  325,  323,  322,  321,  320,  319,  318,
      316,  315,  313,  312,  311,  310,  309,  308,  307,  306,
      304,  303,  301,  300,  298,  297,  295,  294,  292,  291,
      289,  288,  287,  286,  285,  284,  283,  282,  280,  278,
      276,  274,  273,  272,  271,  270,  269,  268,  266,  264,
      263,  262,  260,  259,  257,  256,  255,  254,  253,  252,
      251,  250,  247,  245,  244,  243,  241,  240,  239,  237,

      235,  234,  232,  229,  228,  226,  224,  223,  222,  221,
      219,  215,  214,  212,  210,  209,  206,  205,  201,  195,
      192,  191,  190,  188,  184,  182,  179,  177,  174,  173,
      172,  170,  165,  164,  163,  162,  161,  160,  159,  157,
      155,  154,  153,  152,  151,  150,  149,  148,  145,  142,
      138,  137,  136,  135,  134,  133,  132,  126,  125,  118,
      117,  115,  114,  113,  112,  108,  103,  102,  101,   99,
       86,   85,   72,   71,   66,   65,   55,   54,   52,   50,
       49,   48,   47,   46,   39,   35,   34,   32,   31,   27,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,

      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      380,  380,  380,  380,  380,  380
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "final.l"
#define INITIAL 0
#line 2 "final.l"
    #include<stdio.h>
    #include<string.h>
    #include <stdlib.h>
    #include <stdbool.h>
    #include <ctype.h>
    #include "final.tab.h"

    // header, single, multi, var, print, dis, calc_val, if, till
    int tempCounter[10];

    int blockBalancer = 0;
    int stack[100];
    int stackSize = 0;

    const int MAXIMUM_VAR_SIZE = 10;

    char error[200];

    // extern
    char lastDataType[10];
    char *outBuffer = NULL;
    int outBufferSize = 0;
    bool isLastIfValid = false;
    //extern

    int commentCounter = 0;
    int comment_depth = 0;
    char *comment_buffer = NULL;
    
    bool canDeclareHeader = true;
    bool isMainBlockFound = false;
    bool isCommingFromMain = false;
    bool isCommingFromVar = false;

    size_t buffer_length = 0;

    int bracketCounter=0;

    char *removeRedundant(char*);

    void insertImport(char*);

    // variable
    const int MAXIMUM_VARIABLE_LENGTH = 200;

    int pushState(int id){
        stackSize++;
        stack[stackSize] = id;
        return id;
    }

    int popState(){
        if(stackSize > 0) stackSize--;
        return stack[stackSize];
    }

    void inc(int index){
        tempCounter[index]++;
    }

    void initSingleComment(){
        commentCounter++;
        printf("\nSingle line comment: %s\n",yytext);
    }
    
    void appendToBuffer(char ch){
        comment_buffer = (char*) realloc(comment_buffer, buffer_length + 1);
        buffer_length += sprintf(comment_buffer + buffer_length, "%c", ch);
    }

    void appendTextToBuffer(char* ch){

        if( strncmp(ch,"/*",2) == 0) comment_depth++;
        if( strncmp(ch,"*/",2) == 0) comment_depth--;
        comment_buffer = (char*) realloc(comment_buffer, buffer_length + strlen(ch) );  
        buffer_length += sprintf(comment_buffer + buffer_length, ch);
    }

    void initMultiComment(){
        comment_depth = 1; 
        buffer_length = 2;
        comment_buffer = (char*) malloc(3);

        memset(comment_buffer, 0, 3);
        strcat(comment_buffer, "/*");
    }

    void resetBuffer(){
        free(comment_buffer);
        comment_buffer = NULL;
        buffer_length = 0;
    }

    void process_comment() {
        commentCounter++;
        printf("\nCaptured comment: %s\n\n", comment_buffer);
        //printf("Multi-line comment found\n");
    }

    void stopProgram(char *error){
        printf("%s\n",error);
        free(comment_buffer);
        exit(1);
    }
    
    void checkForEnd(){
        if (comment_depth == 0) {
            BEGIN(INITIAL);
            process_comment();
            resetBuffer();
        }
        else if(comment_depth < 0){
            resetBuffer();
            stopProgram("Invalid comment found");
        }
    }

    void initMain(){
        canDeclareHeader = false;
        //printf("execution started\n");
    }

    void processHeader(){
        if(!canDeclareHeader){
            stopProgram("Header must be at top");
            return;
        }
        
    }

    void initVarSec(char *temp){
        char *type = removeRedundant(temp);
        strcpy(lastDataType,type);
        canDeclareHeader = false;
    }

    void sendNumber(char *text){
        double num = 0;
        sscanf(text, "%lf", &num);
        yylval.num = num;
        //printf("======%lf=====",num);
    }

    void initOutBuffer(){
        outBuffer = (char*) malloc(1);
        memset(outBuffer, 0, 1);
        outBufferSize = 1;
    }

    char* removeLpRp(char *val){
        char *op = malloc(14*sizeof(char));
        char *temp = strdup(val);
        strncpy(op,temp+1, strlen(temp) - 2 );
        return op;
    }

#define COMMENT 1

#define MAIN 2

#define VAR_SEC 3

#define IF_SEC 4

#define IGNORE_SEC 5

#define DISCARD_SEC 6

#define LOOP_SEC 7

#define LOOP_BODY_SEC 8

#define OUT_SEC 9

#define PROTO_SEC 10

#define FUNC_SEC 11

#define FUNC_SEC_VAR 12

#line 882 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 227 "final.l"


#line 1036 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 381 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 891 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 229 "final.l"
{ inc(1); initSingleComment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 230 "final.l"
{ initMultiComment(); BEGIN( pushState(COMMENT) ); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 233 "final.l"
{ inc(1); initSingleComment(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 234 "final.l"
{ inc(1); initSingleComment(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 235 "final.l"
{ inc(1); initSingleComment(); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 236 "final.l"
{ inc(1); initSingleComment(); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 237 "final.l"
{ inc(1); initSingleComment(); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 238 "final.l"
{ inc(1); initSingleComment(); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 239 "final.l"
{ inc(1); initSingleComment(); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 240 "final.l"
{ inc(1); initSingleComment(); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 241 "final.l"
{ inc(1); initSingleComment(); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 242 "final.l"
{ inc(1); initSingleComment(); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 243 "final.l"
{ inc(1); initSingleComment(); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 244 "final.l"
{ inc(1); initSingleComment(); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 246 "final.l"
{ initMultiComment(); BEGIN( pushState(COMMENT) ); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 247 "final.l"
{ initMultiComment(); BEGIN( pushState(COMMENT) ); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 248 "final.l"
{ initMultiComment(); BEGIN( pushState(COMMENT) ); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 249 "final.l"
{ initMultiComment(); BEGIN( pushState(COMMENT) ); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 250 "final.l"
{ initMultiComment(); BEGIN( pushState(COMMENT) ); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 251 "final.l"
{ initMultiComment(); BEGIN( pushState(COMMENT) ); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 252 "final.l"
{ initMultiComment(); BEGIN( pushState(COMMENT) ); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 253 "final.l"
{ initMultiComment(); BEGIN( pushState(COMMENT) ); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 254 "final.l"
{ initMultiComment(); BEGIN( pushState(COMMENT) ); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 255 "final.l"
{ initMultiComment(); BEGIN( pushState(COMMENT) ); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 256 "final.l"
{ initMultiComment(); BEGIN( pushState(COMMENT) ); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 258 "final.l"
{ appendTextToBuffer("/*"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 260 "final.l"
{ 
    appendTextToBuffer("*/"); checkForEnd(); 
    if(comment_depth == 0){ inc(2); BEGIN( popState() ); }
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 264 "final.l"
{ appendTextToBuffer("|"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 265 "final.l"
{ appendToBuffer(yytext[0]); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 267 "final.l"
{ insertImport(yytext); inc(0); processHeader();}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 269 "final.l"
{ 
    //printf("m_type: -%s-\n",yytext);
    BEGIN( pushState(PROTO_SEC) ); 
    char *type = removeRedundant(yytext);
    yylval.name =  strdup( type );
    return FUNC_TYPE;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 277 "final.l"
{ 
    //printf("type: -%s-\n",yytext); 
    char *type = removeRedundant(yytext);
    yylval.name =  strdup( type );
    return FUNC_TYPE; 
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 283 "final.l"
{ 
    //printf("name: -%s-\n",yytext); 
    yylval.name = strdup(yytext);
    return FUNC_NAME; 
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 289 "final.l"
{ return *yytext; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 290 "final.l"
{ return *yytext; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 291 "final.l"
{ BEGIN( popState() ); return *yytext; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 293 "final.l"
{ 
    blockBalancer++;
    //printf("main start %s\n",yytext); 
    initMain(); 
    BEGIN( pushState(MAIN) );
    return ENTRY_POINT;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 301 "final.l"
{
    //printf("main data type %s\n",yytext);
    initVarSec(yytext); 
    char *type = removeRedundant(yytext);
    yylval.name =  strdup( type );
    BEGIN( pushState(VAR_SEC) );
    return DATA_TYPE;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 310 "final.l"
{  
    initOutBuffer();
    BEGIN( pushState(OUT_SEC) );
    return OUTPUT;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 316 "final.l"
{
    inc(7);
    BEGIN( pushState(IF_SEC) );
    return JUST_IN_CASE;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 322 "final.l"
{
    inc(8);
    BEGIN( pushState(LOOP_SEC) );
    return TILL;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 328 "final.l"
{
    //printf("----%s----",yytext);
    BEGIN( pushState(FUNC_SEC) );
    yylval.name = strdup(yytext);
    return FUNC_NAME;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 335 "final.l"
{
    //printf("----%s----",yytext);
    BEGIN( pushState(FUNC_SEC_VAR) );
    yylval.name = strdup(yytext);
    return FUNC_NAME;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 342 "final.l"
{ return *yytext; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 343 "final.l"
{ BEGIN( popState() ); return *yytext; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 344 "final.l"
{ yylval.name = strdup(yytext); return VAR_CON; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 347 "final.l"
{ yylval.name = strdup(yytext); return VAR_CON; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 349 "final.l"
{
    return *yytext;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 353 "final.l"
{
    BEGIN( popState() );
    return *yytext;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 358 "final.l"
{
    yylval.name = strdup(yytext);
    BEGIN( pushState(VAR_SEC) );
    return VAR;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 364 "final.l"
{
    sendNumber(yytext);
    return NUMBER;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 368 "final.l"
{
    yylval.name = removeLpRp(yytext);
    return ARITH_OPE;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 372 "final.l"
{
    yylval.name = strdup(yytext);
    return VAR;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 376 "final.l"
{ return *strdup(yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 377 "final.l"
{ return *strdup(yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 378 "final.l"
{
    BEGIN( popState() );
    return *strdup(yytext);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 382 "final.l"
{}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 385 "final.l"
{
    //printf("Discard section\n");
    inc(5);
    BEGIN( pushState(DISCARD_SEC) );
    return DISCARD;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 392 "final.l"
{
    //printf("\nFrom discard only:-%s-\n",yytext);
    yylval.name = strdup(yytext);
    return VAR;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 397 "final.l"
{ return *yytext; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 398 "final.l"
{ BEGIN( popState() ); return *yytext; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 401 "final.l"
{ 
    yylval.name = strdup(yytext);
    return OUTPUT_VC;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 405 "final.l"
{ 
    yylval.name = strdup(yytext);
    return OUTPUT_VC;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 409 "final.l"
{
    return OUTPUT_SEP;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 412 "final.l"
{
    inc(4);
    BEGIN( popState() );
    return OUTPUT_END;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 418 "final.l"
{ return *yytext; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 419 "final.l"
{ return END_POINT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 421 "final.l"
{ yylval.name = removeLpRp(yytext); return COND_OPE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 422 "final.l"
{ return AND; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 423 "final.l"
{ return OR; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 424 "final.l"
{ yylval.name = strdup(yytext); return VAR_CON; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 425 "final.l"
{ 
    //popState(); // popping if section and taking to main section arki
    popState();

    char *valid = isLastIfValid ? "True" : "False";
    printf("\nIf condition is %s\n",valid);
    if(!isLastIfValid){
        bracketCounter=1;
        BEGIN( pushState(IGNORE_SEC) );
    }
    else{
        BEGIN(pushState(MAIN));
    }
    return *yytext;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 440 "final.l"
{}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 442 "final.l"
{ bracketCounter++; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 443 "final.l"
{ 
    bracketCounter--;
    if(bracketCounter == 0){
        BEGIN( popState() );
        return END_POINT;
    }
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 450 "final.l"
{}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 453 "final.l"
{ return *yytext; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 454 "final.l"
{ return END_POINT; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 455 "final.l"
{ yylval.name = removeLpRp(yytext); return COND_OPE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 456 "final.l"
{ yylval.name = strdup(yytext); return VAR_CON; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 458 "final.l"
{ BEGIN( pushState(LOOP_BODY_SEC) ); return *yytext; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 460 "final.l"
{
    yylval.name = strdup(yytext);
    BEGIN( pushState(VAR_SEC) );
    return VAR;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 465 "final.l"
{}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 466 "final.l"
{
    popState();
    BEGIN( popState() );
    return END_POINT;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 472 "final.l"
{}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 474 "final.l"
{
    blockBalancer--;
    BEGIN( popState() );
    return END_POINT;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 480 "final.l"
{ }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 481 "final.l"
{ }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 483 "final.l"
ECHO;
	YY_BREAK
#line 1691 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(MAIN):
case YY_STATE_EOF(VAR_SEC):
case YY_STATE_EOF(IF_SEC):
case YY_STATE_EOF(IGNORE_SEC):
case YY_STATE_EOF(DISCARD_SEC):
case YY_STATE_EOF(LOOP_SEC):
case YY_STATE_EOF(LOOP_BODY_SEC):
case YY_STATE_EOF(OUT_SEC):
case YY_STATE_EOF(PROTO_SEC):
case YY_STATE_EOF(FUNC_SEC):
case YY_STATE_EOF(FUNC_SEC_VAR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 381 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 381 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 380);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 483 "final.l"


int yywrap(){
    return 1;
}
