/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 34
#define YY_END_OF_BUFFER 35
static yyconst short int yy_accept[198] =
    {   0,
       33,   33,    0,    0,    0,    0,   29,   29,   14,   14,
        0,    0,    0,    0,    0,    0,   35,   34,   33,   34,
       34,   34,    3,    3,    8,    9,    8,    8,   29,   34,
       34,   34,   34,   34,   34,   26,   15,   14,   15,   15,
       20,   20,   20,   19,   22,   21,   34,   34,   33,    5,
        4,    0,    0,    0,    2,    7,    6,   29,    0,    0,
       28,   27,    0,    0,    0,    0,    0,    0,   17,    0,
       14,    0,   16,    0,   10,    0,   11,    0,    0,   19,
        0,    0,    0,    0,    0,    0,   31,    0,   32,    4,
        4,    0,    0,   27,   27,    0,    0,    0,    0,    0,

       17,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   25,    0,    0,    0,
       24,   12,   13,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       18,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    1,    0,    0,   18,    0,    0,    0,    0,
        0,   30,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   23,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    5,
        6,    7,    1,    8,    1,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,   12,    1,
       13,    1,    1,    1,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       15,   15,   15,   15,   15,   15,   16,   17,   18,   19,

       20,   21,   22,   14,   23,   14,   14,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   14,   14,
       14,   14,   35,    1,   36,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[37] =
    {   0,
        1,    1,    1,    2,    1,    3,    1,    4,    5,    1,
        6,    7,    8,    9,   10,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    1,    1
    } ;

static yyconst short int yy_base[219] =
    {   0,
        0,    2,   33,    0,    4,    6,   69,    0,  105,    0,
      139,  142,  543,  542,  177,    0,  577,  712,   15,   12,
      551,  541,  712,  559,  712,  712,  518,  519,   18,  520,
       17,    2,  144,  145,  147,  712,  712,  518,  514,  151,
      712,  210,  161,  712,  712,  712,  516,  211,   26,  712,
      516,  489,  500,  503,  712,  712,  712,  150,  509,  162,
      712,  508,  212,  213,  150,  216,  217,  214,  218,  220,
      506,  224,  712,  230,  712,  236,  712,  235,  231,  712,
      247,  263,  249,  504,  251,  253,  712,  256,  712,  502,
      712,  476,  469,  495,  712,  266,  267,  277,  280,  278,

      288,  292,  295,  292,  294,  467,  130,  256,  469,  303,
      449,  289,  290,  456,  445,  451,  712,  315,  311,  298,
      304,  712,  712,  328,  440,  336,  359,  430,  422,  434,
      329,  330,  340,  337,  360,   26,  385,  369,  408,  431,
      366,  370,  332,  457,  420,  423,  418,  363,  380,  332,
      413,  351,  397,  404,  409,  400,  480,  368,    0,  411,
      413,  371,  503,  363,  358,  412,  410,  348,    0,  418,
      438,  436,  712,  338,  458,  361,  476,  419,    0,    0,
      327,  460,  484,  488,  440,  326,  307,  309,  287,  270,
      257,  236,  249,  170,  121,  712,  712,  529,  539,  549,

      559,  565,  573,  581,  589,  597,  605,  614,  622,  631,
      641,  650,  658,  667,  676,  684,  692,  701
    } ;

static yyconst short int yy_def[219] =
    {   0,
      198,  198,  197,    3,  199,  199,  197,    7,  197,    9,
      200,  200,  201,  201,  197,   15,  197,  197,  197,  197,
      197,  197,  197,  202,  197,  197,  197,  197,  197,  203,
      197,  204,  204,  204,  204,  197,  197,  205,  197,  206,
      197,  197,  207,  197,  197,  197,  208,  209,  197,  197,
      210,  197,  197,  202,  197,  197,  197,  197,  203,  204,
      197,  211,  197,  204,  197,  204,  204,  204,  204,  204,
      205,  206,  197,  197,  197,  206,  197,  197,  197,  197,
      207,  197,  212,  208,  209,  197,  197,  209,  197,  210,
      197,  197,  197,  211,  197,  197,  197,  204,  204,  204,

      197,  204,  197,  197,  197,  197,  197,  197,  197,  212,
      110,  110,  110,  110,  197,  197,  197,  204,  204,  204,
      197,  197,  197,  213,  197,  214,  214,  110,  197,  197,
      204,  204,  204,  213,  197,  215,  213,  110,  216,  216,
      140,  140,  140,  217,  127,  197,  197,  204,  204,  197,
      197,  215,  215,  215,  215,  215,  197,  140,  140,  140,
      140,  140,  217,  163,  140,  137,  140,  140,  140,  140,
      140,  140,  197,  197,  204,  197,  218,  215,  163,  163,
      197,  197,  213,  215,  215,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,    0,  197,  197,  197,

      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197
    } ;

static yyconst short int yy_nxt[749] =
    {   0,
      197,   19,   19,   19,   19,   63,   26,  197,   26,   20,
       27,   20,   27,   28,   65,   28,   49,   49,   50,   58,
       58,   51,   21,   61,   21,  197,   62,   49,   49,  150,
       22,  151,   22,   23,   23,   18,   23,   23,   23,   23,
       23,   24,   23,   23,   23,   23,   24,   23,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   23,   23,   18,
       29,   29,   30,   18,   18,   18,   18,   18,   31,   18,
       18,   18,   32,   18,   32,   32,   32,   33,   32,   34,
       32,   35,   32,   32,   32,   32,   32,   32,   32,   32,

       32,   32,   32,   18,   36,   37,   37,   18,   38,   37,
       37,   37,   37,   37,   39,   37,   37,   37,   40,   37,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   37,
       37,   18,   42,   43,   18,   42,   43,   63,   63,  124,
       63,   58,   58,   96,   74,  196,   65,   65,   75,   65,
       97,  124,   77,   78,   81,   63,   66,   69,   68,   82,
       67,   82,   70,   44,   65,  195,   44,   18,   18,   18,
       47,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       48,   18,   48,   48,   48,   48,   48,   48,   48,   48,

       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   18,   18,   79,   86,   63,   63,   63,   87,   63,
       63,  101,   89,   63,   65,   65,   65,   74,   65,   65,
       65,   75,   65,   74,   79,   77,   78,   75,  103,   74,
      100,   77,   78,   75,   80,  104,   98,   77,   78,   99,
       81,  102,  105,  194,   86,   82,   86,   82,   87,   86,
       87,  193,   89,   87,   89,   80,  105,   89,  111,   96,
      112,   82,  113,   82,  114,  124,   97,   97,  117,  192,
       63,   63,  106,   63,  107,  191,  108,  124,  109,   65,
       65,  101,   65,  120,  118,  121,  119,  105,  103,  122,

       65,   63,  104,  123,   65,  104,  105,   63,  127,  127,
       65,  190,  189,  106,   63,  107,   65,  108,   63,  109,
      126,  126,  111,   65,  112,  188,  113,   65,  114,  133,
      131,  134,   63,   63,  132,  150,  135,  151,  135,  137,
      134,   65,   65,  121,  135,  135,  138,  135,  187,  149,
      136,  165,   65,  186,  150,  140,  151,  141,  148,  142,
      158,  143,  137,  150,  176,  151,   63,  135,  135,  138,
      135,  181,  157,  136,  151,   65,  158,  135,  140,  138,
      141,  175,  142,  121,  143,  164,  180,  144,  137,  164,
      165,  179,   65,  135,  158,  135,  158,  163,  158,  158,

      150,  163,  151,  150,  153,  151,  154,  150,  155,  151,
      156,  157,  150,  151,  151,  166,  176,  151,  135,  178,
      167,  174,  150,  177,  151,  177,  173,  159,  177,  160,
      164,  161,  164,  162,  157,  177,  151,  164,  158,  158,
      177,  158,  163,  150,  163,  151,  158,  177,  139,  163,
      159,  147,  160,  146,  161,  165,  162,  164,  145,  163,
      166,  182,  151,   63,  158,  135,  158,  167,  124,  163,
       65,  136,   65,  130,  129,  128,  169,  126,  170,  183,
      171,  151,  172,  157,  135,  151,  184,  183,  125,  151,
      136,  150,  135,  151,  135,  124,  135,   95,  184,  106,

      116,  107,  115,  108,   91,  109,  166,   84,  151,   71,
       95,  135,   59,  167,   55,   93,   92,  136,   91,   84,
       73,   71,  169,   59,  170,   57,  171,   56,  172,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   54,
       55,   54,   53,   54,   60,   52,  197,   46,   46,  197,
      197,   60,   64,  197,  197,  197,   64,  197,   64,   64,
       72,  197,  197,  197,  197,  197,  197,   72,   76,  197,

       76,  197,   76,   76,   76,   76,   83,  197,  197,   83,
       83,  197,  197,   83,   83,   85,  197,  197,  197,  197,
      197,  197,   85,   88,  197,   88,  197,   88,   88,  197,
       88,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,  110,  197,  197,  197,  110,  197,  197,  110,  136,
      197,  197,  136,  136,  197,  197,  136,  136,  139,  197,
      197,  139,  139,  197,  197,  139,  139,  152,  152,  197,
      197,  152,  197,  197,  152,  158,  158,  197,  197,  158,
      197,  197,  158,  168,  168,  197,  168,  168,  197,  197,

      168,  168,  185,  185,  197,  185,  185,  197,  197,  185,
      185,   17,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197
    } ;

static yyconst short int yy_chk[749] =
    {   0,
        0,    1,    1,    2,    2,   32,    5,    0,    6,    1,
        5,    2,    6,    5,   32,    6,   19,   19,   20,   29,
       29,   20,    1,   31,    2,    0,   31,   49,   49,  136,
        1,  136,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,   11,   11,   11,   12,   12,   12,   33,   34,  107,
       35,   58,   58,   65,   40,  195,   33,   34,   40,   35,
       65,  107,   40,   40,   43,   60,   33,   35,   34,   43,
       33,   43,   35,   11,   60,  194,   12,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   42,   48,   63,   64,   68,   48,   66,
       67,   69,   48,   70,   63,   64,   68,   72,   66,   67,
       69,   72,   70,   74,   79,   72,   72,   74,   78,   76,
       68,   74,   74,   76,   42,   78,   66,   76,   76,   67,
       81,   70,   83,  193,   85,   81,   86,   81,   85,   88,
       86,  192,   85,   88,   86,   79,   82,   88,   83,   96,
       83,   82,   83,   82,   83,  108,   96,   97,   97,  191,
       98,  100,   82,   99,   82,  190,   82,  108,   82,   98,
      100,  101,   99,  100,   98,  102,   99,  105,  103,  104,

      101,  120,  104,  104,  102,  103,  110,  121,  112,  113,
      120,  189,  188,  105,  119,  105,  121,  105,  118,  105,
      112,  113,  110,  119,  110,  187,  110,  118,  110,  120,
      118,  124,  131,  132,  119,  150,  124,  150,  124,  126,
      134,  131,  132,  133,  126,  134,  126,  134,  186,  132,
      126,  143,  133,  181,  152,  126,  152,  126,  131,  126,
      143,  126,  127,  135,  176,  135,  148,  127,  135,  127,
      135,  174,  138,  127,  138,  148,  168,  138,  127,  138,
      127,  148,  127,  149,  127,  141,  165,  127,  137,  142,
      162,  164,  149,  137,  141,  137,  158,  141,  142,  162,

      153,  142,  153,  156,  137,  156,  137,  154,  137,  154,
      137,  139,  155,  139,  155,  166,  151,  166,  167,  156,
      167,  147,  178,  154,  178,  153,  146,  139,  155,  139,
      160,  139,  161,  139,  140,  154,  140,  170,  167,  160,
      155,  161,  160,  185,  161,  185,  170,  178,  145,  170,
      140,  130,  140,  129,  140,  172,  140,  171,  128,  140,
      144,  175,  144,  182,  172,  144,  171,  144,  125,  171,
      175,  144,  182,  116,  115,  114,  144,  111,  144,  177,
      144,  177,  144,  157,  177,  157,  177,  183,  109,  183,
      177,  184,  183,  184,  183,  106,  184,   94,  184,  157,

       93,  157,   92,  157,   90,  157,  163,   84,  163,   71,
       62,  163,   59,  163,   54,   53,   52,  163,   51,   47,
       39,   38,  163,   30,  163,   28,  163,   27,  163,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  202,
       24,  202,   22,  202,  203,   21,   17,   14,   13,    0,
        0,  203,  204,    0,    0,    0,  204,    0,  204,  204,
      205,    0,    0,    0,    0,    0,    0,  205,  206,    0,

      206,    0,  206,  206,  206,  206,  207,    0,    0,  207,
      207,    0,    0,  207,  207,  208,    0,    0,    0,    0,
        0,    0,  208,  209,    0,  209,    0,  209,  209,    0,
      209,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  211,  211,  211,  211,  211,  211,  211,  211,  211,
      211,  212,    0,    0,    0,  212,    0,    0,  212,  213,
        0,    0,  213,  213,    0,    0,  213,  213,  214,    0,
        0,  214,  214,    0,    0,  214,  214,  215,  215,    0,
        0,  215,    0,    0,  215,  216,  216,    0,    0,  216,
        0,    0,  216,  217,  217,    0,  217,  217,    0,    0,

      217,  217,  218,  218,    0,  218,  218,    0,    0,  218,
      218,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "code.l"
#define INITIAL 0
#line 2 "code.l"
    #include<stdio.h>
    #include<string.h>
    #include <stdlib.h>
    #include <stdbool.h>
    #include <ctype.h>

    int stack[100];
    int stackSize = 0;

    // variable
    struct VAR *vars = 0;

    int varSize = 0;
    const int MAXIMUM_VAR_SIZE = 10;

    char error[200];
    char lastDataType[10];

    int commentCounter = 0;
    int comment_depth = 0;
    char *comment_buffer = NULL;

    bool canDeclareHeader = true;
    bool isMainBlockFound = false;
    bool isCommingFromMain = false;
    bool isCommingFromVar = false;
    bool isLastIfValid = false;

    size_t buffer_length = 0;

    int pushState(int id){
        stackSize++;
        stack[stackSize] = id;
        return id;
    }

    int popState(){
        if(stackSize > 0) stackSize--;
        return stack[stackSize];
    }

    bool isLastOneIf(int ifs){
        if(stackSize > 1){
            if( stack[stackSize-1] == ifs){
                return true;
            }
        }
        return false;
    }


    // variable
    const int MAXIMUM_VARIABLE_LENGTH = 200;
    
    struct VAR{
        char name[200];
        double value;
    };
    
    void insertIntoLL(char *name, double val){}

    struct VAR* getVariable(char* name){
        for(int i=0; i<varSize; i++){
            if( strcmp(name,vars[i].name) == 0 ) return &vars[i];
        }
        return NULL;
    }
    
    void stopProgram(char *error){
        printf("%s\n",error);
        free(vars);
        free(comment_buffer);
        exit(1);
    }

    bool doesVariableExists(char *name){
        //printf("Variable size: %d\n",varSize);
        for(int i=0; i<varSize; i++){
            if( strcmp(name,vars[i].name) == 0 ) return true;
        }
        return false;
    }

    char* removeRedundant(char *source){
        int len = strlen(source);

        char temp[len+1];
        int j = 0;
        for(int i=0; i<len; i++){
            //printf("%d, ", source[i]);
            if( source[i] == ' ' || 
                source[i] == ',' ||
                source[i] == ';' ||
                source[i] == '\t' ||
                source[i] == '\n' ||
                source[i] == 32
            )continue;

            temp[j] = source[i];
            j++;
        }

        temp[j] = '\0';
        char *dest;
        dest = malloc(j*sizeof(char));
        strcpy(dest,temp);
        //printf("\n%s\n",dest);
        return dest;
    }

    void extractNameValue(char *nameVal, char *name, double* val){
        char *temp;
        //printf("Extract name value: %s\n",nameVal);
        temp = removeRedundant(nameVal);
        //printf("-%s-\n",temp);
        sscanf(temp, "%[^=]=%lf", name, val);
        free(temp);
    }

    bool addVariable(char* name){
        int size = varSize;

        for(int i=0; i<size; i++){
            if( strcmp(name,vars[i].name) == 0 ){
                stopProgram("Variable is already defined");
                return false;
            }
        }

        vars = (struct VAR *) realloc(vars,(size+2)*MAXIMUM_VAR_SIZE*sizeof(struct VAR));
        if(vars == NULL){
            printf("Why null\n");
        }
        strcpy(vars[size].name, name);
        varSize = size+1;
        
        return true;
    }


    void runHeader(int check){
        if(!check){
            stopProgram("Invalid header format");
        }

        if(!canDeclareHeader){
            printf("Header must be at top of proram\n");
            return;
        }
        else{
            printf("Imported %s\n",yytext);
        }

    }

    void exceptHeader(){
        canDeclareHeader = false;
    }

    void initSingleComment(){
        exceptHeader();
        commentCounter++;
    }

    void resetBuffer(){
        free(comment_buffer);
        comment_buffer = NULL;
        buffer_length = 0;
    }

    void process_comment() {
        commentCounter++;
        //printf("Captured comment: %s\n", comment_buffer);
    }
    
    void checkForEnd(){
        if (comment_depth == 0) {
            BEGIN(INITIAL);
            process_comment();
            resetBuffer();
        }
        else if(comment_depth < 0){
            resetBuffer();
            stopProgram("Invalid comment found");
        }
    }

    void appendToBuffer(char ch){
        comment_buffer = (char*) realloc(comment_buffer, buffer_length + 1);
        buffer_length += sprintf(comment_buffer + buffer_length, "%c", ch);
    }

    void appendTextToBuffer(char* ch){

        if( strncmp(ch,"/*",2) == 0) comment_depth++;
        if( strncmp(ch,"*/",2) == 0) comment_depth--;
        comment_buffer = (char*) realloc(comment_buffer, buffer_length + strlen(ch) );  
        buffer_length += sprintf(comment_buffer + buffer_length, ch);
    }

    void initMultiComment(){
        exceptHeader();
        comment_depth = 1; 
        buffer_length = 2;
        comment_buffer = (char*) malloc(3);

        memset(comment_buffer, 0, 3);

        strcat(comment_buffer, "/*");
    }

    void initMain(){
        canDeclareHeader = false;
        printf("execution started\n");
    }

    void stopMain(){
        printf("Execution done\n");
        isMainBlockFound = true;
    }

    void initVarSec(char *type){
        strcpy(lastDataType,type);
        canDeclareHeader = false;
    }

    void assignValue(char *name, double val){
        for(int i=0; i<varSize; i++){
            if( strcmp(vars[i].name,name) == 0){
                vars[i].value = val;
                break;
            }
        }
    }

    void removeVariable(char *name){
        name = removeRedundant(name);

        if( !doesVariableExists(name) ) return;
        
        for(int i=0; i<varSize; i++){
            if( strcmp(vars[i].name,name) == 0){

                //vars[i].value = val;
                break;
            }
        }
    }

    void declareVariable(char *name, double val){
        name = removeRedundant(name);

        if( !addVariable(name) ){
            char message[50];
            strcpy(message,"Duplicate variable found ");
            strcat(message,name);
            stopProgram(message);
            return;
        }

        assignValue(name,val);
    }

    void processVariable(char *nameVal){
        //printf("nameVal %s\n",nameVal);

        char name[20];
        double value;
        extractNameValue(nameVal,name,&value);
        declareVariable(name,value);
    }

    void updateValue(char *nameVal){
        //printf("Passed %s\n",nameVal);
        char name[20];
        double val;
        extractNameValue(nameVal,name,&val);
        //printf("Extracted %s %ld\n",name,val);

        if( !doesVariableExists(name) ){
            char message[50];
            strcpy(message, "Variable doesn't exists: ");
            strcat(message,name);

            stopProgram(message);
            return;
        }
        //printf("Value not assigned\n");
        assignValue(name,val);
        //printf("Value assigned\n");
    }

    bool isNumber(char* num){
        bool count = 0;
        for(int i=0; i<strlen(num); i++){
            if( num[i] == '.' && count == 0 ) { count=1; continue; }
            if( !isdigit(num[i]) ) return false;
        }
        return true;
    }

    bool isCondOpValid(char* op){
        char arr[6][5] = { "lt","gt","eq","neq","le","ge" };
        for(int i=0; i<6; i++){
            if(strcmp(arr[i],op) == 0) return true;
        }
        return false;
    }

    bool isConditionValid(double left, char* op, double right){
        if( strncmp(op,"lt",2) == 0) return (left < right);
        if( strncmp(op,"gt",2) == 0) return (left > right);
        if( strncmp(op,"eq",2) == 0) return (left == right);

        if( strncmp(op,"le",2) == 0) return (left <= right);
        if( strncmp(op,"ge",2) == 0) return (left >= right);
        if( strncmp(op,"neq",2) == 0) return (left != right); // 2 fine also
    }

    void processIfBody(char *body){
        //processed body
        char pBody[strlen(body)];

        int i=0;
        while(body[i] != '(')i++;
        i++;

        int j=0;
        while(body[i] != ')'){ pBody[j] = body[i]; i++; j++; }
        pBody[j] = '\0';

        char leftVal[50], operator[10], rightVal[50];
        sscanf(pBody, "%49s %9s %49s", leftVal, operator, rightVal);

        double left = 0, right = 0;

        if( isNumber(leftVal) ) left = strtod(leftVal,NULL);
        else{
            struct VAR *val = getVariable(leftVal);
            if(val == NULL) {
                printf("%s\n",leftVal);
                stopProgram("Invalid variable in if");
            }
            else left = (*val).value;
        }

        if( isNumber(rightVal) ) right = strtod(rightVal,NULL);
        else{
            struct VAR *val = getVariable(rightVal);
            if(val == NULL) {
                printf("%s\n",rightVal);
                stopProgram("Invalid variable in if");
            }
            else right = (*val).value;
        }

        if( !isCondOpValid(operator) ){
            stopProgram("Invalid operator in if");
            return;
        }

        isLastIfValid = isConditionValid(left,operator,right);

        //printf("body of if is: %d\n",isLastIfValid);

        //printf("extracted: %s %s %s\n",leftVar,operator,rightVal);
    }

#define HEADER 1

#define COMMENT 2

#define MAIN 3

#define VAR_SEC 4

#define IF_SEC 5

#define IGNORE_SEC 6

#define DISCARD_SEC 7

#line 978 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 417 "code.l"

#line 1131 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 198 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 712 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 418 "code.l"
{ BEGIN(pushState(HEADER)); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 420 "code.l"
{ runHeader(1); BEGIN( popState() ); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 422 "code.l"
{ runHeader(0); BEGIN(popState()); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 424 "code.l"
{ initSingleComment(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 426 "code.l"
{ initMultiComment(); BEGIN( pushState(COMMENT) ); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 428 "code.l"
{ appendTextToBuffer("/*"); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 429 "code.l"
{ 
    appendTextToBuffer("*/"); checkForEnd(); 
    if(comment_depth == 0){
        BEGIN( popState() );
    } 
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 438 "code.l"
{ appendToBuffer(yytext[0]); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 439 "code.l"
{ appendTextToBuffer("\n"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 441 "code.l"
{ declareVariable(yytext,0); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 442 "code.l"
{
    declareVariable(yytext,0);
    BEGIN( popState() );
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 447 "code.l"
{ processVariable(yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 448 "code.l"
{
    processVariable(yytext);
    BEGIN( popState() );
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 452 "code.l"
{}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 453 "code.l"
{ stopProgram("Invalid character found");}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 454 "code.l"
{ 
    initMultiComment();
    BEGIN( pushState(COMMENT) );    
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 460 "code.l"
{ BEGIN( pushState(IF_SEC) ); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 462 "code.l"
{ processIfBody(yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 463 "code.l"
{ 
    popState(); // main section arki
    if(isLastIfValid){
        BEGIN(pushState(MAIN));
    }
    else{
        BEGIN( pushState(IGNORE_SEC) );
    }
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 473 "code.l"
{}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 475 "code.l"
{ 
    int state = popState();
    BEGIN( popState() );
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 479 "code.l"
{}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 481 "code.l"
{ 
    //printf("main start %s\n",yytext); 
    initMain(); 
    BEGIN( pushState(MAIN) ); 
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 486 "code.l"
{
    //printf("main data type %s\n",yytext);
    initVarSec(yytext); 
    BEGIN( pushState(VAR_SEC) );
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 491 "code.l"
{ 
    //printf("main assign %s\n",yytext);
    updateValue(yytext);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 495 "code.l"
{
    //stopMain();
    //int val = popState();
    //printf(" main end popped %s %d %d\n",yytext,val,MAIN);
    BEGIN( popState() );
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 501 "code.l"
{
    //printf("main comment %s\n",yytext);
    initSingleComment();
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 505 "code.l"
{
    //printf("main multi %s\n",yytext);
    initMultiComment(); 
    BEGIN( pushState(COMMENT) );
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 510 "code.l"
{ }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 512 "code.l"
{
    //printf("Discard section\n");
    BEGIN( pushState(DISCARD_SEC) );
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 517 "code.l"
{
    printf("Discard variable %s\n",yytext);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 520 "code.l"
{
    printf("discard Variable only last %s\n",yytext);
    BEGIN( popState() );
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 525 "code.l"
{ }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 527 "code.l"
ECHO;
	YY_BREAK
#line 1440 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(HEADER):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(MAIN):
case YY_STATE_EOF(VAR_SEC):
case YY_STATE_EOF(IF_SEC):
case YY_STATE_EOF(IGNORE_SEC):
case YY_STATE_EOF(DISCARD_SEC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 198 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 198 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 197);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 527 "code.l"


int yywrap(){
    return 1;
}


int main(){

    // char name[20];
    // double value;
    // extractNameValue("y = 5333",name,&value);
    // printf("%s %lf\n",name,value);
    // return 0;

    // while(1){
    //     char arr[10];
    //     scanf("%s",&arr);
    //     if(strncmp(arr,"-1",2) == 0) break;
    //     addVariable(arr);
    // }

    yyin = fopen("input.txt","r");
    yylex();

    // if(!isMainBlockFound){
    //     stopProgram("Incomplete main block");
    // }

    for(int i=0; i<varSize; i++){
        printf("%s : %3lf\n",vars[i].name,vars[i].value);
    }
    stopProgram("");

    if( strlen(error) == 0 ){
        printf("Total comment: %d\n",commentCounter);
        printf("Program compiled successfully\n");
    }
    else{
        printf("Error: %s\n",error);
    }

}
