/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
static yyconst short int yy_accept[292] =
    {   0,
       64,   64,    0,    0,    5,    5,   63,   63,   33,   33,
        0,    0,   49,   49,    0,    0,    0,    0,   59,   59,
       61,   61,    0,    0,    0,    0,    0,    0,   66,   65,
       64,   65,   65,   65,   65,   65,   65,    6,    5,    5,
        6,    6,   63,   65,   65,   26,   26,   26,   26,   26,
       26,   26,   62,   33,   30,   65,   65,   27,   32,   31,
       29,   29,   29,   29,   29,   29,   49,   42,   65,   47,
       47,   47,   47,   47,   47,   47,   47,   48,   43,   52,
       50,   51,   36,   37,   35,   59,   53,   65,   56,   56,
       56,   56,   56,   56,   57,   54,   61,   65,   58,   60,

       40,   65,   65,   40,   65,   39,   39,   15,   65,   14,
       13,   13,   13,   13,   13,   23,   65,   24,   25,   24,
       64,    2,    1,    0,    0,    0,    0,    0,    0,    5,
        4,    3,   63,    9,    8,   22,   26,   26,   26,   26,
       26,   26,   26,   26,   33,   27,    7,    0,   27,   29,
       29,   29,   29,   29,   29,   49,   47,    0,   47,   47,
       47,   44,   47,   46,   35,   59,   56,    0,   56,   56,
       55,   56,   61,    0,   60,   58,   40,    0,   40,    0,
       38,    0,   41,   40,   39,    0,   39,   39,   16,   13,
       13,   13,   13,   13,   24,    0,   24,   24,    1,    1,

        0,    0,    0,   11,    0,    0,    8,    8,   22,   26,
       26,   26,   26,   26,   26,   26,   27,   28,   47,   45,
       56,   41,   39,   13,   13,   12,   13,   24,    0,    0,
        0,    0,   26,   26,   26,   18,   26,   26,   21,   13,
       13,    0,    0,    0,   26,   26,   26,   26,   13,    0,
        0,   26,   26,   26,    0,    0,   26,   26,   26,    0,
        0,   34,   26,   19,   10,    0,   26,   19,    0,   20,
        0,   20,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   17,   17,
        0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    1,    6,
        7,    8,    1,    9,    1,   10,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,   13,    1,
       14,    1,    1,   15,   16,   16,   17,   16,   16,   16,
       16,   16,   18,   16,   16,   16,   16,   16,   16,   19,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
        1,    1,    1,    1,    1,    1,   20,   21,   22,   23,

       24,   25,   26,   16,   27,   28,   16,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   16,   16,
       40,   16,   41,    1,   42,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[43] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    3,    1,    1,    1,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        1,    1
    } ;

static yyconst short int yy_base[310] =
    {   0,
        0,   38,    0,    0,    2,    4,   77,    0,  119,    0,
        0,    0,  161,    0,    1,    3,  203,    0,  245,    0,
      287,    0,  329,    0,  371,    0,  413,    0,  698,  699,
        6,    6,  665,  667,    0,  658,  662,  699,   16,   18,
      682,  684,   26,   24,    0,    0,    6,  662,  659,  651,
      653,  660,  699,  682,  699,  673,  676,   12,  699,  699,
        0,  660,  655,  643,  656,  641,   44,  699,  666,   38,
        0,  646,  642,   27,   29,  651,  639,  699,  699,  699,
      699,  699,  699,  699,    0,   52,  699,  661,   46,    0,
      638,   33,   35,  647,  699,  699,   65,   33,    0,  699,

      452,  665,   56,  665,  656,   61,    0,  699,  654,  699,
        0,  634,  636,  633,  631,  699,  650,  448,  699,    0,
      460,  699,  658,  622,  627,  625,  620,  636,  628,  462,
      699,  699,  464,  699,  651,    0,    0,  617,  614,  619,
      613,  613,  621,  618,  642,  633,  699,  632,  458,    0,
      620,   37,  613,  611,  619,  469,  627,  626,  463,    0,
      614,    0,  602,    0,    0,  474,  623,  622,  468,    0,
        0,  599,  479,  453,  699,    0,  479,  480,  628,  626,
      699,  481,  626,  625,  616,  615,  477,    0,  699,    0,
      588,  593,  587,  596,  610,  609,  480,    0,  617,  699,

      598,  598,  585,  699,  579,  592,  611,  699,    0,  591,
      591,  591,  606,  572,  577,  578,  594,    0,  593,    0,
      592,  599,  590,  580,  580,    0,  576,  586,  568,  559,
      560,  567,  573,  563,  554,  699,  572,  552,    0,  559,
      550,  562,  548,  562,  548,  558,  550,  551,  555,  574,
      573,  553,  558,  543,    0,  534,  568,  551,  564,  556,
      536,  699,  531,  562,  699,  538,  540,  559,  539,  557,
      556,  555,  533,  479,  472,  473,  467,  486,  470,  464,
      448,   15,  492,  493,  496,  497,  465,  470,   30,   22,
      699,  511,  515,  519,   12,  521,  523,  525,  527,  529,

      531,  535,  537,  539,  541,  545,  549,  551,  554
    } ;

static yyconst short int yy_def[310] =
    {   0,
      292,  292,  292,  292,  293,  293,  291,    7,  291,    9,
      292,  292,  291,   13,  294,  294,  291,   17,  291,   19,
      291,   21,  291,   23,  291,   25,  291,   27,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  295,  296,  296,  296,  296,  296,
      296,  296,  291,  291,  291,  291,  291,  291,  291,  291,
      297,  297,  297,  297,  297,  297,  291,  291,  291,  291,
      298,  298,  298,  298,  298,  298,  298,  291,  291,  291,
      291,  291,  291,  291,  299,  291,  291,  291,  291,  300,
      300,  300,  300,  300,  291,  291,  291,  291,  301,  291,

      291,  302,  291,  291,  291,  291,  303,  291,  291,  291,
      304,  304,  304,  304,  304,  291,  291,  291,  291,  305,
      291,  291,  306,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  307,  308,  296,  296,  296,  296,
      296,  296,  296,  296,  291,  291,  291,  291,  291,  297,
      297,  297,  297,  297,  297,  291,  291,  291,  291,  298,
      298,  298,  298,  298,  299,  291,  291,  291,  291,  300,
      300,  300,  291,  291,  291,  301,  291,  291,  291,  302,
      291,  291,  291,  291,  291,  291,  291,  303,  291,  304,
      304,  304,  304,  304,  291,  291,  291,  305,  306,  291,

      291,  291,  291,  291,  291,  291,  307,  291,  308,  296,
      296,  296,  296,  296,  296,  296,  291,  297,  291,  298,
      291,  291,  291,  304,  304,  304,  304,  291,  291,  291,
      291,  291,  296,  296,  296,  291,  296,  296,  296,  304,
      304,  291,  291,  291,  296,  296,  296,  296,  304,  291,
      291,  296,  296,  296,  309,  291,  296,  296,  296,  309,
      291,  291,  296,  291,  291,  291,  296,  291,  291,  296,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
        0,  291,  291,  291,  291,  291,  291,  291,  291,  291,

      291,  291,  291,  291,  291,  291,  291,  291,  291
    } ;

static yyconst short int yy_nxt[742] =
    {   0,
      291,   31,   31,   39,   40,   39,   40,  121,  121,   41,
       32,   41,   42,  122,   42,  136,  123,  130,  130,  130,
      130,  148,   33,  149,   34,  290,   35,  133,  133,  126,
      127,  134,  138,  290,  135,   36,  174,  139,   37,   31,
       31,   81,   82,   81,   82,  156,  156,  158,   32,  159,
      162,  283,  162,  166,  166,  168,  171,  169,  171,  182,
       33,  218,   34,  162,   35,  162,  173,  173,  183,  171,
      186,  171,  187,   36,  175,  218,   37,   30,   43,   43,
       30,   30,   30,   30,   30,   30,   30,   44,   30,   30,
       30,   45,   46,   46,   46,   46,   46,   46,   46,   47,

       46,   48,   46,   49,   50,   46,   46,   46,   46,   51,
       46,   46,   46,   52,   46,   46,   46,   30,   53,   30,
       30,   30,   54,   30,   30,   30,   30,   55,   56,   57,
       58,   59,   60,   30,   61,   61,   61,   61,   62,   61,
       61,   63,   61,   61,   61,   61,   61,   61,   64,   61,
       61,   61,   61,   65,   66,   61,   61,   61,   61,   30,
       30,   30,   67,   67,   30,   30,   68,   68,   30,   30,
       69,   30,   70,   30,   30,   30,   71,   71,   71,   71,
       72,   71,   71,   71,   73,   71,   74,   71,   71,   75,
       71,   76,   77,   71,   71,   71,   71,   71,   71,   71,

       71,   78,   79,   30,   30,   30,   30,   30,   30,   30,
       30,   83,   30,   30,   30,   84,   30,   30,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   30,   30,   30,   86,   86,   30,   30,
       87,   87,   30,   30,   88,   30,   89,   30,   30,   30,
       90,   90,   90,   90,   90,   90,   90,   90,   91,   90,
       92,   90,   90,   93,   90,   94,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   95,   96,   30,   97,   97,
       98,   30,   30,   30,   30,   30,   30,   30,   30,   30,

       30,   30,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   30,  100,   30,
       30,   30,  101,  102,   30,  103,   30,  104,  105,   30,
      106,   30,   30,   30,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,   30,
       30,   30,   30,   30,   30,   30,  108,  109,   30,  110,
       30,   30,   30,   30,   30,   30,  111,  111,  111,  111,
      111,  111,  111,  112,  111,  113,  111,  114,  111,  111,

      111,  111,  111,  111,  111,  111,  111,  111,  111,  115,
      111,   30,   30,   30,   30,   30,   30,   30,  116,  116,
       30,  116,  117,   30,  118,  119,   30,   30,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,   30,   30,  177,  174,  196,  178,  197,
      179,  121,  121,  130,  130,  133,  133,  148,  288,  149,
      156,  156,  158,  288,  159,  166,  166,  168,  282,  169,
      173,  173,  177,  182,  182,  178,  186,  179,  187,  196,
      281,  197,  183,  183,  175,  284,  284,  285,  285,  286,

      286,  280,  287,  287,  279,  289,  278,  277,  276,  275,
      289,   30,   30,   30,   30,   38,   38,   38,   38,   80,
       80,   80,   80,  137,  137,  150,  150,  160,  160,  165,
      165,  170,  170,  176,  176,  180,  180,  180,  180,  188,
      188,  190,  190,  198,  198,  199,  199,  199,  199,  207,
      207,  207,  207,  209,  209,  260,  274,  260,  272,  273,
      272,  271,  268,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  259,  258,  257,  256,  255,  226,  254,
      253,  213,  252,  251,  250,  204,  226,  249,  248,  247,
      213,  246,  245,  244,  243,  204,  242,  228,  226,  241,

      240,  223,  222,  221,  219,  217,  239,  238,  237,  236,
      235,  234,  233,  208,  204,  232,  231,  230,  229,  200,
      228,  195,  227,  226,  225,  224,  223,  185,  184,  222,
      181,  184,  171,  221,  167,  162,  220,  219,  157,  218,
      218,  218,  218,  217,  146,  145,  216,  215,  214,  213,
      212,  211,  210,  208,  206,  205,  204,  203,  202,  201,
      200,  195,  194,  193,  192,  191,  189,  185,  184,  181,
      172,  171,  167,  164,  163,  162,  161,  157,  155,  154,
      153,  152,  151,  147,  146,  145,  144,  143,  142,  141,
      140,  132,  131,  129,  128,  125,  124,  291,   29,  291,

      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291
    } ;

static yyconst short int yy_chk[742] =
    {   0,
        0,    1,    1,    5,    5,    6,    6,   31,   31,    5,
        1,    6,    5,   32,    6,  295,   32,   39,   39,   40,
       40,   58,    1,   58,    1,  290,    1,   43,   43,   35,
       35,   44,   47,  289,   44,    1,   98,   47,    1,    2,
        2,   15,   15,   16,   16,   67,   67,   70,    2,   70,
       74,  282,   75,   86,   86,   89,   92,   89,   93,  103,
        2,  152,    2,   74,    2,   75,   97,   97,  103,   92,
      106,   93,  106,    2,   98,  152,    2,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,

       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,

       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,  101,  174,  118,  101,  118,
      101,  121,  121,  130,  130,  133,  133,  149,  287,  149,
      156,  156,  159,  288,  159,  166,  166,  169,  281,  169,
      173,  173,  177,  178,  182,  177,  187,  177,  187,  197,
      280,  197,  178,  182,  174,  283,  284,  283,  284,  285,

      286,  279,  285,  286,  278,  287,  277,  276,  275,  274,
      288,  292,  292,  292,  292,  293,  293,  293,  293,  294,
      294,  294,  294,  296,  296,  297,  297,  298,  298,  299,
      299,  300,  300,  301,  301,  302,  302,  302,  302,  303,
      303,  304,  304,  305,  305,  306,  306,  306,  306,  307,
      307,  307,  307,  308,  308,  309,  273,  309,  272,  271,
      270,  269,  268,  267,  266,  264,  263,  261,  260,  259,
      258,  257,  256,  254,  253,  252,  251,  250,  249,  248,
      247,  246,  245,  244,  243,  242,  241,  240,  238,  237,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  225,

      224,  223,  222,  221,  219,  217,  216,  215,  214,  213,
      212,  211,  210,  207,  206,  205,  203,  202,  201,  199,
      196,  195,  194,  193,  192,  191,  186,  185,  184,  183,
      180,  179,  172,  168,  167,  163,  161,  158,  157,  155,
      154,  153,  151,  148,  146,  145,  144,  143,  142,  141,
      140,  139,  138,  135,  129,  128,  127,  126,  125,  124,
      123,  117,  115,  114,  113,  112,  109,  105,  104,  102,
       94,   91,   88,   77,   76,   73,   72,   69,   66,   65,
       64,   63,   62,   57,   56,   54,   52,   51,   50,   49,
       48,   42,   41,   37,   36,   34,   33,   29,  291,  291,

      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "final.l"
#define INITIAL 0
#line 2 "final.l"
    #include<stdio.h>
    #include<string.h>
    #include <stdlib.h>
    #include <stdbool.h>
    #include <ctype.h>
    #include "final.tab.h"

    // header, single, multi, var, print, dis, calc_val, if, till
    int tempCounter[10];

    int blockBalancer = 0;
    int stack[100];
    int stackSize = 0;

    const int MAXIMUM_VAR_SIZE = 10;

    char error[200];

    // extern
    char lastDataType[10];
    char *outBuffer = NULL;
    int outBufferSize = 0;
    bool isLastIfValid = false;
    //extern

    int commentCounter = 0;
    int comment_depth = 0;
    char *comment_buffer = NULL;
    
    bool canDeclareHeader = true;
    bool isMainBlockFound = false;
    bool isCommingFromMain = false;
    bool isCommingFromVar = false;

    size_t buffer_length = 0;

    int bracketCounter=0;

    char *removeRedundant(char*);

    // variable
    const int MAXIMUM_VARIABLE_LENGTH = 200;

    int pushState(int id){
        stackSize++;
        stack[stackSize] = id;
        return id;
    }

    int popState(){
        if(stackSize > 0) stackSize--;
        return stack[stackSize];
    }

    void inc(int index){
        tempCounter[index]++;
    }

    void initSingleComment(){
        commentCounter++;
        printf("\nSingle line comment: %s\n",yytext);
    }
    
    void appendToBuffer(char ch){
        comment_buffer = (char*) realloc(comment_buffer, buffer_length + 1);
        buffer_length += sprintf(comment_buffer + buffer_length, "%c", ch);
    }

    void appendTextToBuffer(char* ch){

        if( strncmp(ch,"/*",2) == 0) comment_depth++;
        if( strncmp(ch,"*/",2) == 0) comment_depth--;
        comment_buffer = (char*) realloc(comment_buffer, buffer_length + strlen(ch) );  
        buffer_length += sprintf(comment_buffer + buffer_length, ch);
    }

    void initMultiComment(){
        comment_depth = 1; 
        buffer_length = 2;
        comment_buffer = (char*) malloc(3);

        memset(comment_buffer, 0, 3);
        strcat(comment_buffer, "/*");
    }

    void resetBuffer(){
        free(comment_buffer);
        comment_buffer = NULL;
        buffer_length = 0;
    }

    void process_comment() {
        commentCounter++;
        printf("\nCaptured comment: %s\n\n", comment_buffer);
        //printf("Multi-line comment found\n");
    }

    void stopProgram(char *error){
        printf("%s\n",error);
        free(comment_buffer);
        exit(1);
    }
    
    void checkForEnd(){
        if (comment_depth == 0) {
            BEGIN(INITIAL);
            process_comment();
            resetBuffer();
        }
        else if(comment_depth < 0){
            resetBuffer();
            stopProgram("Invalid comment found");
        }
    }

    void initMain(){
        canDeclareHeader = false;
        //printf("execution started\n");
    }

    void processHeader(){
        if(!canDeclareHeader){
            stopProgram("Header must be at top");
            return;
        }
        printf("header: -%s-\n",yytext); 
    }

    void initVarSec(char *temp){
        char *type = removeRedundant(temp);
        strcpy(lastDataType,type);
        canDeclareHeader = false;
    }

    void sendNumber(char *text){
        double num = 0;
        sscanf(text, "%lf", &num);
        yylval.num = num;
        //printf("======%lf=====",num);
    }

    void initOutBuffer(){
        outBuffer = (char*) malloc(1);
        memset(outBuffer, 0, 1);
        outBufferSize = 1;
    }

#define HEADER 1

#define COMMENT 2

#define MAIN 3

#define VAR_SEC 4

#define VAR_CALC_SEC 5

#define IF_SEC 6

#define IGNORE_SEC 7

#define DISCARD_SEC 8

#define LOOP_SEC 9

#define LOOP_BODY_SEC 10

#define OUT_SEC 11

#define PROTO_SEC 12

#define FUNC_SEC 13

#line 801 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 221 "final.l"

#line 954 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 292 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 699 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 222 "final.l"
{ inc(1); initSingleComment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 223 "final.l"
{ initMultiComment(); BEGIN( pushState(COMMENT) ); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 225 "final.l"
{ appendTextToBuffer("/*"); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 227 "final.l"
{ 
    appendTextToBuffer("*/"); checkForEnd(); 
    if(comment_depth == 0){ inc(2); BEGIN( popState() ); }
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 232 "final.l"
{ appendTextToBuffer("|"); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 234 "final.l"
{ appendToBuffer(yytext[0]); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 236 "final.l"
{ initMultiComment(); BEGIN( pushState(COMMENT) ); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 238 "final.l"
{ inc(1); initSingleComment(); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 240 "final.l"
{ initMultiComment();  BEGIN( pushState(COMMENT) ); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 242 "final.l"
{ inc(0); processHeader();}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 244 "final.l"
{ 
    //printf("m_type: -%s-\n",yytext);
    BEGIN( pushState(PROTO_SEC) ); 
    char *type = removeRedundant(yytext);
    yylval.name =  strdup( type );
    return FUNC_TYPE;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 252 "final.l"
{ 
    //printf("type: -%s-\n",yytext); 
    char *type = removeRedundant(yytext);
    yylval.name =  strdup( type );
    return FUNC_TYPE; 
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 258 "final.l"
{ 
    //printf("name: -%s-\n",yytext); 
    yylval.name = strdup(yytext);
    return FUNC_NAME; 
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 264 "final.l"
{ return *yytext; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 265 "final.l"
{ return *yytext; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 266 "final.l"
{ BEGIN( popState() ); return *yytext; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 268 "final.l"
{ 
    blockBalancer++;
    //printf("main start %s\n",yytext); 
    initMain(); 
    BEGIN( pushState(MAIN) );
    return ENTRY_POINT;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 276 "final.l"
{
    //printf("main data type %s\n",yytext);
    initVarSec(yytext); 
    char *type = removeRedundant(yytext);
    yylval.name =  strdup( type );
    BEGIN( pushState(VAR_SEC) );
    return DATA_TYPE;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 285 "final.l"
{  
    initOutBuffer();
    BEGIN( pushState(OUT_SEC) );
    return OUTPUT;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 291 "final.l"
{
    inc(7);
    BEGIN( pushState(IF_SEC) );
    return JUST_IN_CASE;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 297 "final.l"
{
    inc(8);
    BEGIN( pushState(LOOP_SEC) );
    return TILL;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 303 "final.l"
{
    printf("----%s----",yytext);
    BEGIN( pushState(FUNC_SEC) );
    yylval.name = strdup(yytext);
    return FUNC_NAME;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 309 "final.l"
{
    return *yytext;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 313 "final.l"
{ yylval.name = strdup(yytext); return VAR_CON; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 315 "final.l"
{
    BEGIN( popState() );
    return *yytext;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 320 "final.l"
{
    yylval.name = strdup(yytext);
    BEGIN( pushState(VAR_SEC) );
    return VAR;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 326 "final.l"
{
    sendNumber(yytext);
    return NUMBER;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 330 "final.l"
{
    yylval.name = strdup(yytext);
    return ARITH_OPE;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 334 "final.l"
{
    yylval.name = strdup(yytext);
    return VAR;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 338 "final.l"
{ return *strdup(yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 339 "final.l"
{ return *strdup(yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 340 "final.l"
{
    BEGIN( popState() );
    return *strdup(yytext);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 344 "final.l"
{}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 347 "final.l"
{
    //printf("Discard section\n");
    inc(5);
    BEGIN( pushState(DISCARD_SEC) );
    return DISCARD;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 354 "final.l"
{
    //printf("\nFrom discard only:-%s-\n",yytext);
    yylval.name = strdup(yytext);
    return VAR;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 359 "final.l"
{ return *yytext; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 360 "final.l"
{ BEGIN( popState() ); return *yytext; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 363 "final.l"
{ 
    yylval.name = strdup(yytext);
    return OUTPUT_VC;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 367 "final.l"
{ 
    yylval.name = strdup(yytext);
    return OUTPUT_VC;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 371 "final.l"
{
    return OUTPUT_SEP;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 374 "final.l"
{
    inc(4);
    BEGIN( popState() );
    return OUTPUT_END;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 380 "final.l"
{ return *yytext; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 381 "final.l"
{ return END_POINT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 383 "final.l"
{ yylval.name = strdup(yytext); return COND_OPE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 384 "final.l"
{ return AND; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 385 "final.l"
{ return OR; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 386 "final.l"
{ yylval.name = strdup(yytext); return VAR_CON; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 387 "final.l"
{ 
    //popState(); // popping if section and taking to main section arki
    popState();

    char *valid = isLastIfValid ? "True" : "False";
    printf("\nIf condition is %s\n",valid);
    if(!isLastIfValid){
        bracketCounter=1;
        BEGIN( pushState(IGNORE_SEC) );
    }
    else{
        BEGIN(pushState(MAIN));
    }
    return *yytext;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 402 "final.l"
{}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 404 "final.l"
{ bracketCounter++; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 405 "final.l"
{ 
    bracketCounter--;
    if(bracketCounter == 0){
        BEGIN( popState() );
        return END_POINT;
    }
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 412 "final.l"
{}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 415 "final.l"
{ return *yytext; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 416 "final.l"
{ return END_POINT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 417 "final.l"
{ yylval.name = strdup(yytext); return COND_OPE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 418 "final.l"
{ yylval.name = strdup(yytext); return VAR_CON; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 420 "final.l"
{ BEGIN( pushState(LOOP_BODY_SEC) ); return *yytext; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 422 "final.l"
{
    yylval.name = strdup(yytext);
    BEGIN( pushState(VAR_SEC) );
    return VAR;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 427 "final.l"
{}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 428 "final.l"
{
    popState();
    BEGIN( popState() );
    return END_POINT;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 434 "final.l"
{}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 436 "final.l"
{
    blockBalancer--;
    BEGIN( popState() );
    return END_POINT;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 442 "final.l"
{ }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 443 "final.l"
{ }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 445 "final.l"
ECHO;
	YY_BREAK
#line 1484 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(HEADER):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(MAIN):
case YY_STATE_EOF(VAR_SEC):
case YY_STATE_EOF(VAR_CALC_SEC):
case YY_STATE_EOF(IF_SEC):
case YY_STATE_EOF(IGNORE_SEC):
case YY_STATE_EOF(DISCARD_SEC):
case YY_STATE_EOF(LOOP_SEC):
case YY_STATE_EOF(LOOP_BODY_SEC):
case YY_STATE_EOF(OUT_SEC):
case YY_STATE_EOF(PROTO_SEC):
case YY_STATE_EOF(FUNC_SEC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 292 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 292 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 291);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 445 "final.l"


int yywrap(){
    return 1;
}
